#!/bin/sh
echo '{"streams":[{"codec_type":"video","codec_name":"h264","width":512,"height":512,"avg_frame_rate":"15/1"},{"codec_type":"audio","codec_name":"aac"}],"format":{"format_name":"mov,mp4,m4a,3gp,3g2,mj2","duration":"13.904000","bit_rate":"1708492"}}'
